/**:
  ros__parameters:
    bag_file: "svd_route_0"
    storage_id: "mcap"
    topic_names:
      - "/zed/zed_node/rgb/image_rect_color"
      - "/zed/zed_node/pose"
      - "/zed/zed_node/point_cloud/cloud_registered"
      - "/zed/zed_node/odom"
    topic_types:
      - "sensor_msgs/msg/Image"
      - "geometry_msgs/msg/PoseStamped"
      - "sensor_msgs/msg/PointCloud2"
      - "nav_msgs/msg/Odometry"
    max_bag_size: 1000000000
    max_bag_duration: 0
