/**:
  ros__parameters:
    bag_file: "test_bag_4cams"
    storage_id: "mcap"
    topic_names:
      - "/zed_multi/zed1/left/image_rect_color"
      - "/zed_multi/zed1/point_cloud/cloud_registered"
      - "/zed_multi/zed2/left/image_rect_color"
      - "/zed_multi/zed2/point_cloud/cloud_registered"
      - "/zed_multi/zed3/left/image_rect_color"
      - "/zed_multi/zed3/point_cloud/cloud_registered"
      - "/zed_multi/zed4/left/image_rect_color"
      - "/zed_multi/zed4/point_cloud/cloud_registered"
    topic_types:
      - "sensor_msgs/msg/Image"
      - "sensor_msgs/msg/PointCloud2"
      - "sensor_msgs/msg/Image"
      - "sensor_msgs/msg/PointCloud2"
      - "sensor_msgs/msg/Image"
      - "sensor_msgs/msg/PointCloud2"
      - "sensor_msgs/msg/Image"
      - "sensor_msgs/msg/PointCloud2"
    max_bag_size: 1000000000
    max_bag_duration: 0
